kind: Deployment
apiVersion: apps/v1beta2
metadata:
  name: sftp
  namespace: sftp
  labels:
    ops: sftp
spec:
  # how many pods and indicate which strategy we want for rolling update
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      ops: sftp
  template:
    metadata:
      labels:
        ops: sftp
    spec:
      #secrets and config
      volumes:
      - name: sftp-host-keys
        secret:
          secretName: sftp-host-keys
          defaultMode: 0600
      - name: sftp-user-conf
        secret:
          secretName: sftp-user-conf
          defaultMode: 0600
      - name: sftp-data-vol
        persistentVolumeClaim:
          claimName: sftp-data-vol
      # - name: sftp-data
      #   hostPath:
      #     path: "/sftp-data"
      #     type: DirectoryOrCreate
      containers:
      #the sftp server itself
      - name: sftp
        image: yakworks/sftp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 22
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /etc/ssh/ssh_host_ed25519_key
          name: sftp-host-keys
          subPath: ssh_host_ed25519_key
          readOnly: true
        - mountPath: /etc/ssh/ssh_host_ed25519_key.pub
          name: sftp-host-keys
          subPath: ssh_host_ed25519_key.pub
          readOnly: true
        - mountPath: /etc/ssh/ssh_host_rsa_key
          name: sftp-host-keys
          subPath: ssh_host_rsa_key
          readOnly: true
        - mountPath: /etc/ssh/ssh_host_rsa_key.pub
          name: sftp-host-keys
          subPath: ssh_host_rsa_key.pub
          readOnly: true
        - mountPath: /etc/sftp/users.conf
          name: sftp-user-conf
          subPath: users.conf
        - mountPath: /data
          name: sftp-data-vol
        # - mountPath: /data
        #   name: sftp-data
