apiVersion: v1
kind: Secret
metadata:
  name: sftp-user-conf
  labels:
    role: sftp
type: Opaque
stringData:
  users.conf: |
    admin:FuB4r::owner
    superu:FuB4r::staff
    ziggy:FuB4r::50
    user1:::users
    user2:FuB4r::100
    user3:FuB4r
