kind: Service
apiVersion: v1
metadata:
  name: sftp
  labels:
    role: sftp
spec:
  type: NodePort
  ports:
  - name: ssh
    port: 30022
    targetPort: 22
    nodePort: 30022
  selector:
    ops: sftp
